### ISSUE TITLE
Aspects éditoriaux

### ISSUE THREAD

**Issue by rysebaert** [rzine-reviews/GWR_Rzine#2]
- Pour les URL généraliser l'usage du {target="_blank"} pour la gestion de l'ouverture des pages Web. 
- Un acronyme utilisé doit systématiquement être défini au moins une première fois (SHS). L'acronyme est défini pour VI et VD, mais je me demande s'il est d'usage dans les papiers académiques de recourrir à cet acronyme systématiquement ?
- J'aime beaucoup le style, que l'on pourrait qualifier de ludique et pédagogue. Néanmoins une relecture ne serait pas inutile, notamment pour des formulations un peu maladroites / familières / redites. Quelques exemples : "notre nouveau modèle devrait donc ressembler à **ça**", "Le risque d’une trop grande colinéarité est de **biaiser** le modèle et notamment de **biaiser** les estimations, "On observe ici qu’à la fin la variable part_agri_nb_emploi n’est donc pas conservé". "(...) s’il faut reconnaître que les types de données en SHS **ne** remplissent pas toujours ces condition", "Ici on donc une autocorrélation spatiale positive et importante". "(...) et les modèle SEM, SAR & cie"    
- Il serait utile d'ajouter certaines références à certains endroits. Notamment quand vous citez Luc Anselin ou discutez d'éléments théoriques. 
- Figure choix du modèle de régression spatiale. Préciser si c'est vous qui avez réalisé cette figure, ou indiquez la source.

**Comment by juliepierson** [comment]
Les 3 premiers points sont normalement ok avec 6d114ab875815ddd0321113c162c98d5f065c19e

**Comment by juliepierson** [comment]
4ème point : ajout de la ref biblio de Luc Anselin pour les LISA avec 41cdb2874871a22d7f14467e2d37981c4662a0dc

**Comment by juliepierson** [comment]
Et pour le dernier point : le schéma a été supprimé, un autre a été ajouté en intro pour expliquer le cheminement global, et comme précisé avec 637cc0c3413ab80789b16342517f6391116ae80d c'est Fred qui l'a fait :-)

**Comment by juliepierson** [comment]
Donc tout devrait être ok pour cette issue je crois !

**Comment by rysebaert** [comment]
Merci !
