### ISSUE TITLE
Usage des packages / code

### ISSUE THREAD

**Issue by rysebaert** [rzine-reviews/GWR_Rzine#3]
- Le code s'exécute sans erreur et est conforme aux sorties présentées dans le html. Il manque juste deux par(mfrox=c(1,1)) à deux endroits pour ne pas hériter des paramètres graphiques de précédentes visualisations:

```
plot(neighbours_epci, coord)
```
et 

```
 mf_map(x = data_immo, 
       var = "res_reg", 
       type = "choro", 
       border = NA,
       lwd = 0.1,
       breaks = breaks_residus,
       pal = palette,
       leg_title = "Valeur centrale =  0\nIntervalle = σ / 2", 
       leg_val_rnd = 1)
```

- Qu'apporte plotly dans la visualisation des histogrammes ? Les possibilités d'interactivité ne sont pas réellement utilisées dans votre exemple. Pourquoi ne pas utiliser des fonctions de base R dans ce cas > hist(x) ?
- Je ne suis pas spécialement convaincu par l'apport des packages gtsummary, qui rallonge inutilement la démonstration.
- Je me demande si vous ne réinventez pas inutilement la poudre avec vos fonctions de limites de classe. Les méthodes de classIntervals {classInt} ne serait-elles pas suffisantes ? Il y a notamment une méthode "sd" basé sur moyenne et écart-type si je ne m'abuse... L'appel de ce package n'est-il pas suffisant ? Ou la méthode `msd` proposée par la fonction mf_get_breaks du package mapsf, qui permet d'ajouter la fonction central=TRUE pour que la moyenne soit centre de classe ? 
- Dans les chunks, faites des retours à la ligne pour éviter les scroll latéraux. Par exemple : 
ceci :
```
# Pour l'occasion on va standardiser notre prix médian. Cela permettra par la suite de le comparer à d'autres variables si d'autres analyses d'autocorrélation spatiale sont réalisées
data_immo$prix_med_z<- (data_immo$prix_med-mean(data_immo$prix_med))/sd(data_immo$prix_med)
```
peut devenir ceci pour éviter de consulter vos commentaires de code utiles en scrollant indéfiniment vers la droite: 
```
# Pour l'occasion on va standardiser notre prix médian. 
# Cela permettra par la suite de le comparer à d'autres variables si d'autres analyses d'autocorrélation 
# spatiale sont réalisées
data_immo$prix_med_z<- (data_immo$prix_med-mean(data_immo$prix_med))/  sd(data_immo$prix_med)
```

**Comment by juliepierson** [comment]
Le 1er point est ok avec d6f93df0f718691ac06c770e6be853e658afd935, merci !

**Comment by juliepierson** [comment]
Pour le 4ème point sur la fonction avec les limites de classe, les méthodes existantes ne permettent pas à ma connaissance de : 
- choisir la valeur centrale (parfois on a besoin que ce soit la moyenne, parfois la valeur 0 par ex.)
- regrouper les classes extrêmes si elles comportent moins de n individus

Mais c'est vrai qu'on pinaille un peu :sweat_smile: J'ai mis cette fonction dans un fichier à part discr.R, qui est appelé dans le fichier Rmd avec 38e0528734d59371ba85feb5eeca4d714b54bb29. Est-ce que ça te semblerait ok comme ça ?

**Comment by juliepierson** [comment]
Pour le dernier point sur les retours à la ligne dans les commentaires c'est ok normalement. j'ai aussi fait des retours à la ligne dans le code quand il y a une série d'arguments, pour + de clarté (53d22bf65a7dd61be606bb06faca5b3202d793c6)

**Comment by juliepierson** [comment]
Je laisse @lecampiong répondre pour les points 2 et 3 sur plotly et gtsummary :wink:

**Comment by LeCampionG** [comment]
Merci beaucoup pour ces retours. Concernant les packages plotly et gtsummary j'avoue effectivement que leur usage n'est pas indispensable pour la démonstration de l'article. Néanmoins, un des objectif de cet articles est une démocratisation et diffusion des méthodes et il me semble que ces deux packages y participent.

Le package plotly grâce à son intéractivité dans ce contexte permet d'identifier immédiatement qui seront nos outliers et de commencer à réfléchir comment ils devront être taités. En revanche, nous pouvons effectivement améliorier le code pour que l'identifiant apparaisse clairement pour justement identifier sans doute possible les individus concernés. Il me semble que c'est une bonne pratique et du coup l'idée c'était plus de mettre en avant l'utilisation de cette méthode plutôt que l'usage de la fonction hist().

Concernant gtsummary, il permet une lecture plus aisé des résultats. Vue la qualité visuelle des sorties stat de R c'est malgré tout pas inutile notamment pour les lecteurs moins habitué à ces méthodes. Par ailleurs, sa fontionnalité qui permet d'ajouter directement le vif à la sortie est particulièrement pratique dans le cadre d'un diagnostic du modèle sur la question de la multicolinéarité. L'idée là aussi était de proposer une alternative simple qui nous semble intéressante.

**Comment by juliepierson** [comment]
Je crois qu'on a répondu à tous les points sur ce ticket, est-ce que c'est ok ?

**Comment by rysebaert** [comment]
Merci pour vos modifications et ces précisions. OK pour moi.
