### ISSUE TITLE
Cartographies

### ISSUE THREAD

**Issue by rysebaert** [rzine-reviews/GWR_Rzine#4]
- Pour la carte d'EPCI, l'usage de mapsf n'est pas spécialement utile pour ce qui est présenté ici (pas d'habillage et de sémio particulière). Privilégier peut-être un plot(epci_sf$geometry) ? Par ailleurs pour aller plus droit au but (vu que l'article est assez fourni quand même) je me demande si la première illustration à représenter ne serait pas directement la carte de la VD.  
- La carte de la représentation graphique des voisinages n'est pas très lisible. Réduire les marges, jouer sur la symbologie ou faire un zoom serait appréciable. 
- Sur les cartes, ajouter une couche géographique d'habillage de régions faciliterait la localisation des EPCI. Cela vous permettrait aussi d'éviter d'appeler un thème spécifique (couleur de bg différente) ponctuellement pour palier des effets d'une palette de couleur > mf_map(reg, col = NA, lwd = 1.2, add = TRUE)
- dans mf_credits, rajouter l'année de référence dans les sources de la carte (date de téléchargement des données);
- Pour med_vie.coef, inverser la palette de couleur (valeurs fortes dans les tonalités plus claires pour l'instant) ? L'argument rev=TRUE dans mf_get_pal permet de faire ceci. 
- Une simple question pour rendre comparables vos cartes de résidus GWR : ne serait-il pas intéressant d'avoir une discrétisation commune à vos 8 cartes/variables pour les rendre comparables (quantiles des 8 cartes ?), avec une même palette de couleur ? Cela permettrait efficacement d'introduire la représentation suivante.

Voici une proposition de code pour aller en ce sens avec vos données. A vous de voir en fonction de vos objectifs analytiques... 

```
# Sélectionnez tous les noms de colonne avec le nom coef (plusieurs moyens de le faire)
ind <- colnames(data_immo[,grep("coef", colnames(data_immo)), drop = TRUE])
# Quantiles sur ces indicateurs (10 classes)
discr <- quantile(data_immo[,ind, drop = TRUE], probs = seq(0,1,0.1), na.rm = TRUE)

# Palette (rupture à 0)
palette <- mf_get_pal(n = c(4, 5), pal = c("Teal", "Peach"), neutral = "#f5f5f5")

# 8 cartes avec la même discrétisation
par(mfrow = c(4, 2)) 
for (var in colnames(data_immo)[22:29]) {
  # la carte
  mf_map(x = data_immo,
         var = var,
         type = "choro",
         border = "gray",
         lwd = 0.1,
         breaks = discr,
         pal = palette,
         leg_pos = "left",
         leg_title = NA,
         leg_val_rnd = 0)
  mf_title(var)
}
```

- Rendre un peu plus "littéraires" vos cartes en général. Pour prendre l'exemple de la carte des variables contribuant le plus par EPCI : contribmax > nom de la variable / suroccup.t > % logements suroccupés. De la même manière un label d'indicateur en titre de carte n'est pas une pratique très courante...  
- Certains titres de légende ne sont pas très heureux et mériteraient d'être transcrits dans un style un peu plus littéraires : nbsignif_p, nbsignif_t, contribmax... Ils mériteraient aussi d'être harmonisés. Certains évoquent des méthodes de discrétisation (quantile, notamment), d'autres des modèles statistiques, d'autres rien du tout (résidus de GWR)
- Le box suivant est inutile : *Sur ces deux dernières cartes (...) nous avons pris volontairement une liberté avec les règles de sémiologie graphique de Bertin (....) Que les mânes de Bertin nous pardonnent !*
> Selon la sémiologie bertinienne, vous représentez ici une donnée ordonnée dont la somme n'a pas de sens. Vous pouvez de fait tout à fait utiliser de la couleur ordonnée pour restituer vos résultats ;-)

**Comment by juliepierson** [comment]
Pour le 1er point j'ai supprimé la carte des EPCI qui n'est effectivement pas très utile. Dans la même idée pour visualiser les EPCI sans correspondance un peu plus bas j'ai utilisé plot plutôt que mapsf (4469436090e2ed2572305747aa9110a4ed9a93ba).

**Comment by juliepierson** [comment]
2ème point sur la représentation du voisinage (effectivement illisible !) : les marges ont été réduites et les points masqués avec 416509f0227e5a28b6d3172e5bf74d6961fa4487

**Comment by juliepierson** [comment]
4ème point sur l'année des sources ok avec 52e3cf137b01efd49d2cdbeac61423a9f5775c18, j'ai également ajouté les sources pour les cartes où il n'y en avait pas

**Comment by juliepierson** [comment]
J'ai ajouté les régions sur les cartes avec ed795c75899d32fce56c00ade696eeed1ae067e8
Perso je ne suis pas complètement convaincue que ça apporte quelque chose pour la lecture des cartes, je trouve que ça les alourdit un peu, mais j'attends l'avis des collègues !
Sinon la couleur des bordures des symboles de légende est maintenant raccord avec la couleur de bordure des EPCI.

**Comment by juliepierson** [comment]
Ok pour le point 5 sur l'inversion de la palette de couleurs pour la vignette sur le niveau de vie dans les cartes des coefficients avec dd98274202885d5caaaff91135cda46b82ae5b08

**Comment by LeCampionG** [comment]
> J'ai ajouté les régions sur les cartes avec [ed795c7](https://github.com/rzine-reviews/GWR_Rzine/commit/ed795c75899d32fce56c00ade696eeed1ae067e8) Perso je ne suis pas complètement convaincue que ça apporte quelque chose pour la lecture des cartes, je trouve que ça les alourdit un peu, mais j'attends l'avis des collègues ! Sinon la couleur des bordures des symboles de légende est maintenant raccord avec la couleur de bordure des EPCI.

je suis d'accord, à mon sens elles ne sont pas utiles et ne facilitent pas la lecture des cartes.  A titre personnel je préfère sans.

**Comment by juliepierson** [comment]
Pour le point 6

>     Une simple question pour rendre comparables vos cartes de résidus GWR : ne serait-il pas intéressant d'avoir une discrétisation commune à vos 8 cartes/variables pour les rendre comparables (quantiles des 8 cartes ?), avec une même palette de couleur ? Cela permettrait efficacement d'introduire la représentation suivante.

Dans la mesure où la discrétisation est standardisée c'est ok non pour pouvoir comparer les cartes ? Ou j'ai loupé un truc ?

**Comment by juliepierson** [comment]
Normalement les 2 derniers points sont ok aussi, si on n'a rien loupé tout est bon pour cette issue !

**Comment by rysebaert** [comment]
Merci pour ces modifications. Quelques commentaires, vraiment à la marge pour clôturer l'issue:

Les cartes de voisinage sont nettement plus lisbles, vous pouvez juste utilement remplacer ceci

```{r}
proj4string_2154 <- "+proj=lcc +lat_0=46.5 +lon_0=3 +lat_1=49 +lat_2=44 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs"
neighbours_epci_sf <- spdep::nb2lines(neighbours_epci, coords=coord, proj4string=proj4string_2154, as_sf=T)
```
par cela

```{r}
neighbours_epci_sf <- spdep::nb2lines(neighbours_epci, coords = coord, proj4string = "EPSG:2154", as_sf = T)
```
Pour les contours des EPCI, personnellement cela m'aide à me repérer pour interpréter des résultats. Mais si cela introduit de votre point de vue du bruit (et suggère la présence d'une VI d'appartenance territoriale qui n'a pas lieu d'être) peut être mieux vaut-il la supprimer, effectivement. Une solution d'entre-deux peut consister à réduire un peu l'épaisseur de la ligne. A vous de trancher, je ne m'opposerai pas au choix effectué !

**Comment by juliepierson** [comment]
Merci pour ta remarque @rysebaert , c'est ok pour le 1er point avec b8075bf33b48f1e4090102eb7716a63e39036823

Je crois qu'on va laisser comme ça pour les contours des régions !
