### ISSUE TITLE
Graphiques

### ISSUE THREAD

**Issue by rysebaert** [rzine-reviews/GWR_Rzine#5]
- sur le corrplot, on peut éventuellement réduire la taille des labels (tl.cex = .7 au lieu de 1)

**Comment by LeCampionG** [comment]
C'est fait la modification est visible dasn le commit [4a8cfc6](https://github.com/rzine-reviews/GWR_Rzine/commit/4a8cfc6d632dc19441ef643335c341becfa3bd8d)

**Comment by LeCampionG** [comment]
Je me permets de cloturer cet issue pour plus de lisibilité.
