### ISSUE TITLE
Données et manipulations de données

### ISSUE THREAD

**Issue by rysebaert** [rzine-reviews/GWR_Rzine#6]
- La présentation des indicateurs mériterait d'être plus précise. Je pense par exemple au % de logements suroccupés (définition ?), % agriculteurs (% sur quoi ?) ou des indicateurs où il semble que vous manquez d'information (surface < ?). Il faudrait clarifier tout ceci. Rappeler la date de référence des indicateurs en plus des unités de mesure serait aussi utile. 
- Faire le ménage dans le dossier data. Le readme à la racine n'est pas très clair au regard des données réellement mobilisées dans la fiche. Le contenu du dossier à supprimer n'est pas forcément utile. On se doute que ce dossier a été réalisé pour une autre occasion :)
- Plus généralement, ne placer dans ce dossier que les couches géographiques et les fichiers que vous utilisez dans votre fiche serait utile. 
- Pourquoi ne pas mettre les données d'entrées et directement les données centrées réduites ? Présenter la fonction scale() pourrait être utile dans votre exemple, car c'est nécessaire dans la chaîne de traitement. 
- La partie avec les données manquantes ne parait pas très utile. Sûrement à résumer / simplifier.

**Comment by juliepierson** [comment]
Ok pour le 2ème et le 3ème point sur le dossier data avec b564f126d2ed7959fb3b61a911b1de5e88b3f24c, j'avais zappé ça :sweat_smile:

**Comment by juliepierson** [comment]
Ajout d'un lien vers la définition du % de logements suroccupés, + suppression de l'unité pour la densité de pop vu que la variable est centrée réduite avec 8cc9b9fb7bdc6f6713e2dcb3e10aba1a834e1a97

**Comment by juliepierson** [comment]
> Pourquoi ne pas mettre les données d'entrées et directement les données centrées réduites ? Présenter la fonction scale() pourrait être utile dans votre exemple, car c'est nécessaire dans la chaîne de traitement.

Est-ce que ça n'est pas déjà le cas pour les données ? Pour la fonction scale, j'ai mis un lien vers la doc (ce805941a31c456c918059d361736334a71c34ad), et il y a une explication rapide ("il suffit de soustraire chaque valeur par la moyenne puis de diviser par l’écart-type. ")

**Comment by juliepierson** [comment]
Pour le dernier point, on en discute @phraid29 et @LeCampionG !

**Comment by LeCampionG** [comment]
> La partie avec les données manquantes ne parait pas très utile. Sûrement à résumer / simplifier.

Effectivement cette partie peut paraitre longue pour un spécialiste de la donnée spatiale, mais dans le cadre d'une démarche péagogique cela nous semble important de la conserver. En effet cet article s'adresse aussi bien à des spécialiste de données spatiales qui souhaiterai aller vers la statistique spatiale qu'à des spécialiste de la statistique qui souhaiterai aller vers la statistique spatiale et donc manipuler de la données spatiales

**Comment by rysebaert** [comment]
Pour 

> Est-ce que ça n'est pas déjà le cas pour les données ?

Dans le dossier data, je suggérais de mettre les données brutes non standardisées, et d'effectuer un scale() après, pour montrer l'ensemble de la chaîne de traitement à partir de données officielles INSEE. A vous de voir si cela vous semble opportun ou non (pas d'opposition de ma part). De mon point de vue avec vos commentaires dans la partie 1.1 c'est clair aussi. 

Dernière petite chose le point * % petits logements (surface < ?)* est à éclaircir. D'après les données INSEE de logement disponibles, les informations disponibles sur la taille du logement correspondent au nb de pièces par RP (1, 2, 3, 4 ou 5 et plus).

**Comment by LeCampionG** [comment]
> Dans le dossier data, je suggérais de mettre les données brutes non standardisées, et d'effectuer un scale() après, pour montrer l'ensemble de la chaîne de traitement à partir de données officielles INSEE. A vous de voir si cela vous semble opportun ou non (pas d'opposition de ma part). De mon point de vue avec vos commentaires dans la partie 1.1 c'est clair aussi.

Effectivement cela aurait plus clair, mais dans le cadre de ce projet d'article nous avons eu accès aux données déjà standardisés nous pourrions remonter et utiliser les données non centrée-réduite mais nous obligerai à reconstituer la base de données utilisée. Ainsi, si le commentaire de la partie 1.1 vous convient, il nous semble plus simple de s'y tenir.

**Comment by rysebaert** [comment]
OK pour moi
