### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by rysebaert** [rzine-reviews/GWR_Rzine#7]
- On peut éventuellement réduire la taille du texte des tables. 
- Un label des EPCI pourrait être utile. 
- Arrondir les valeurs numériques contenues dans les tableaux (1 ou 2 décimales)
- Pour certains tableaux, le show 10 entries ne fonctionne pas, du fait de l'usage de head(x, 5) dans le code. 
- Pour l'ensemble des tableaux, garder l'identifiant utilisé dans l'ensemble (CODE_SIREN) et le nom de l'EPCI. Cela peut aider à interpréter certains tableaux, comme celui des résidus. Tel quel on ne peut pas en faire grand chose.

**Comment by juliepierson** [comment]
> Un label des EPCI pourrait être utile.

Ok pour les 2 tables concernées (résidus et résultats GWR) avec bf330e58da1f39beb216fbf1fadce26acd4f5dbb

**Comment by juliepierson** [comment]
> Pour certains tableaux, le show 10 entries ne fonctionne pas, du fait de l'usage de head(x, 5) dans le code.

Ok avec 7003785433b13857d52845df94d4a3a2bc023094 et dd0a7c5565da6193a4f02115be8e6852308fc88d

**Comment by juliepierson** [comment]
> Arrondir les valeurs numériques contenues dans les tableaux (1 ou 2 décimales)

Arrondis avec format  : ce00faccf1b6820b58f64a13bde52421100946e7

**Comment by juliepierson** [comment]
> Pour l'ensemble des tableaux, garder l'identifiant utilisé dans l'ensemble (CODE_SIREN) et le nom de l'EPCI. Cela peut aider à interpréter certains tableaux, comme celui des résidus. Tel quel on ne peut pas en faire grand chose.

Du coup je pense que c'est bon avec le commit bf330e58da1f39beb216fbf1fadce26acd4f5dbb non ?

**Comment by rysebaert** [comment]
Merci, c'est tout bon pour moi sur cette issue !
