### ISSUE TITLE
Autre

### ISSUE THREAD

**Issue by rysebaert** [rzine-reviews/GWR_Rzine#8]
- Une suggestion, étant donné le nombre d'étapes important proposé dans cette article, une figure de synthèse résumant l'ensemble des étapes pourrait être utile - depuis la normalisation des valeurs jusqu'aux différentes visualisations issus de la GWR. Ce mémo graphique aiderait le lecteur à se rappeler de la succession des étapes et leur intérêt pour ce type de démonstration.

**Comment by LeCampionG** [comment]
Merci pour cette suggestion, c'est effectivement une très bonne idée!

**Comment by juliepierson** [comment]
Et c'est maintenant chose faite grâce au schéma de @phraid29 :-)
